---
# --------------------------------

- name: 'download archive'
  get_url:
    dest: '{{hashicorp_dir_staging}}/{{consul_target}}'
    timeout: '{{hashicorp_internet_timeout}}'
    url: '{{hashicorp_repo}}/consul/{{consul_version}}/{{consul_target}}'
    validate_certs: false
  tags: [ct-consul]

- name: 'expand archive'
  unarchive:
    src: '{{hashicorp_dir_staging}}/{{consul_target}}'
    dest: '{{hashicorp_dir_bin}}'
    copy: false
  become: true
  ignore_errors: '{{ansible_check_mode}}'
  tags: [ct-consul]

- name: 'push bash include'
  template:
    src: consul.sh.j2
    dest: /usr/local/etc/bash.d/consul.sh
    owner: root
    group: root
    mode: 0644
  become: true
  tags: [ct-consul]

- name: 'directories'
  file:
    state: directory
    path: '{{item}}'
    owner: root
    group: root
    mode: '0755'
  loop: '{{consul_dirs}}'
  become: true
  tags: [ct-consul]

- name: 'system account'
  user:
    name: consul
    comment: 'Consul system account'
    system: true
    state: present
  become: true
  tags: [ct-consul]

- name: 'render {{consul_role}} config'
  template:
    src: '{{consul_role}}.json.j2'
    dest: '{{consul_etc_dir}}/{{consul_role}}.json'
    owner: root
    group: root
    mode: '0600'
  notify: handler_reload_consul
  no_log: true
  become: true
  tags: [ct-consul]

- name: 'render systemd unit file'
  template:
    src: consul-{{consul_role}}.service.j2
    dest: /etc/systemd/system/consul-{{consul_role}}.service
    owner: root
    group: root
    mode: '0600'
  register: reg_service
  become: true
  tags: [ct-consul]

- name: 'see if Datadog is installed (cm=f)'
  stat:
    path: /etc/datadog-agent
  check_mode: false
  register: doggy
  tags: [ct-consul, ct-consul-datadog]

- name: 'render Datadog config file for Consul'
  template:
    src: datadog-consul-conf.yaml.j2
    dest: /etc/datadog-agent/conf.d/consul.d/conf.yaml
    owner: root
    group: root
    mode: '0644'
  when: doggy.stat.isdir is defined and doggy.stat.isdir
  become: true
  tags: [ct-consul, ct-consul-datadog]

- name: 'render Datadog config file for Systemd'
  template:
    src: datadog-systemd-conf.yaml.j2
    dest: /etc/datadog-agent/conf.d/systemd.d/conf.yaml
    owner: root
    group: root
    mode: '0644'
  when: doggy.stat.isdir is defined and doggy.stat.isdir
  become: true
  tags: [ct-consul, ct-consul-datadog]
  # TODO handler to restart Datadog agent

- name: 'consul-{{consul_role}} service to {{consul_state}}'
  systemd:
    name: consul-{{consul_role}}
    state: '{{consul_state}}'
    enabled: true
    daemon_reload: '{{reg_service is changed}}'
  become: true
  tags: [ct-consul]

# --------------------------------
...
